### ISSUE TITLE
새로운 원소 추가 시 현재 원소가 0개라면

### ISSUE THREAD

**Issue by S0YKIM** [MichelleJin12/DataStructure#2]
https://github.com/MichelleJin12/DataStructure/blob/b446189c8309d47d1180e55dd4948b79b9062a97/1.array.c#L50

아직 아무런 데이터도 추가되지 않은 상태에서는 현재 원소 개수가 0개인데, 그렇게 되면 i 가 0 으로 시작하여 [-1] 인덱스에 접근하게 되는 오류가 있습니다!

**Comment by MichelleJin12** [comment]
https://github.com/MichelleJin12/DataStructure/blob/b446189c8309d47d1180e55dd4948b79b9062a97/1.array.c#L50-L64
currentElementCount가 0 일 때는 i가 0부터 시작하기 때문에, position에 음수 값이 들어오지 않는 한 for문 이하는 실행되지 않아요!! 그래서 -1 인덱스에 접근할 경우는 없지만, position에 음수값이 들어올 수 있는 케이스는 가드하는게 좋겠네요~!!! 코멘트 감사드려요~!!!
