### ISSUE TITLE
댕글링 포인터

### ISSUE THREAD

**Issue by S0YKIM** [MichelleJin12/DataStructure#3]
https://github.com/MichelleJin12/DataStructure/blob/174836d4bbb45b9962fd812005d8c2ce93464377/1.array.c#L33

포인터 free 해준 후에 NULL 가리키도록 해서 댕글링 포인터 방지해줍시다~!

**Comment by MichelleJin12** [comment]
https://github.com/MichelleJin12/DataStructure/blob/a48cedc39019b6080d33f885adea06140049d087/main.c#L50-L53
네~!! main.py에서, arr와 lst를 free한 후 NULL로 초기화해주었어요!! 감사합니다~!!
