### ISSUE TITLE
[add] 변수 초기화

### ISSUE THREAD

**Issue by S0YKIM** [MichelleJin12/DataStructure#7]
https://github.com/MichelleJin12/DataStructure/blob/a48cedc39019b6080d33f885adea06140049d087/1.linked_list.c#L17

currentElementCount, headerNode.data, headerNode.pLink 0 으로 초기화하는 과정이 필요하지 않을까요?

**Comment by MichelleJin12** [comment]
초기화하는 코드를 넣었어요~! 감사합니다~!
